name: xnime_app
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    go_router: ^15.1.2
    dio: ^5.8.0+1
    flutter_dotenv: ^5.2.1
    flutter_svg: ^2.1.0
    flutter_launcher_icons: ^0.14.3
    smooth_page_indicator: ^1.2.1
    curved_labeled_navigation_bar: ^2.0.6
    chewie: ^1.11.3
    webview_flutter: ^4.13.0
    http: ^1.4.0
    flutter_native_splash: ^2.4.6
    fancy_shimmer_image: ^2.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#131517"
  image: "assets/logos/Xyutori.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logos/icon_background.png"
  image_path_ios: "assets/logos/icon_background.png"
  # ↓ Dua opsi untuk adaptive icon Android ↓
  android_adaptive_icon_foreground: "assets/logos/icon_foreground.png"
  android_adaptive_icon_background: "assets/logos/icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/poppins/
    - assets/videos/
    - assets/logos/Xyutori.svg
    - assets/logos/Xyutori.png
    - assets/logos/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic